#!/bin/bash

# Copyright (C) 2010 Daniel Garcia Moreno <dani@danigm.net>
# Copyright (C) 2010 Eduardo Robles Elvira <edulix@wadobo.com>
#
# This software may be used and distributed according to the terms of the
# GNU General Public License version 3 or any later version, incorporated
# herein by reference.

export GIT_NOTES_DISPLAY_REF="refs/notes/timetracker"
function show_help {
    echo "usage: git timetrack command [options]"
    echo ""
    echo "    -s, --start             start/continue counting time spent"
    echo "    -k, --start-hacking     start/continue counting time spent, won't stop (only reset) on commit"
    echo "    -p, --stop              stop/pause counting time spent"
    echo "    -r, --reset             reset counting time spent"
    echo "    -e, --set <minutes>     set time spent in minutes"
    echo "    -c, --current           time spent currently in next commit"
    echo "    -a, --amend [<object>]  set currently spent time to last commit or to the given one"
    echo "    -d, --delete [<object>] delete time-spent to last commit or to the given one"
    echo "    -u, --summary [<opts>]  show summary of total time spent. takes similar options as git log"
    echo "    -l, --log [<opts>]      show git log with notes translates to human time"
    echo "    -o, --addhooks          adds post-commit hook and post-merge to the project"
    echo "    -n, --config [<remote>] adds config to the project to pull and push timetrack info"
    echo "    -i, --init              setup timetrack environment, hooks and config for origin"
}

function human_time() {
    s=$1
    if [ -z $s ]; then s=0; fi
    m=0
    while [ $s -ge 60 ]
    do
        m=$(( $m + $s / 60 ))
        s=$(( $s % 60 ))
    done
    h=0
    while [ $m -ge 60 ]
    do
        h=$(( $h + $m / 60 ))
        m=$(( $m % 60 ))
    done

    str=""
    if [ $h -ne 0 ]; then str=$str" $h hours"; fi
    if [ $m -ne 0 ]; then str=$str" $m minutes"; fi
    if [ -z "$str" ]
    then
        str=$str" $s seconds"
    else
        if [ $s -ne 0 ]; then str=$str" $s seconds"; fi
    fi

    echo $str
}

function current_time() {
    start_date=$(git config --get timetrack.start)
    current_date=$(date +%s)
    spent_date=$(git config --get timetrack.spent)
    if [ -z $spent_date ]; then spent_date=0; fi

    if [ $start_date ]
    then
        spent=$(( $spent_date + $current_date - $start_date ))
    else
        if [ $spent_date -gt 0 ]
        then
            spent=$spent_date
        fi
    fi

    echo $spent
}

function user_time_dedication() {
    user=$1
    shift
    alltimes=$(git log --author="$user" $* | grep "Time-spent: " | cut -d":" -f2)

    total=0
    for t in $alltimes
    do
        total=$(( $total + $t ))
    done

    echo $total
}

case $1 in
    -s|--start)
        git config timetrack.start $(date +%s)
        ;;

    -k|--start-hacking)
        git config timetrack.start $(date +%s)
        git config timetrack.hacking "true"
        ;;

    -p|--stop)
        start_date=$(git config --get timetrack.start)
        current_date=$(date +%s)
        spent_date=$(git config --get timetrack.spent)
        if [ -z $spent_date ]; then spent_date=0; fi

        if [ $start_date ]
        then
            spent=$(( $spent_date + $current_date - $start_date ))
            git config --remove-section timetrack 2>/dev/null
            git config timetrack.spent $spent
        else
            echo "Stop before start? I don't think so."
        fi
        ;;

    -c|--current)
        spent=$(current_time)
        if [ -z $spent ]
        then
            echo "There's no time information :("
        else
            echo "time spent in next commit: $(human_time $spent)"
            hacking=$(git config --get timetrack.hacking)
            if [ $hacking ]
            then
                echo "hacking mode activated"
            fi
        fi
        ;;

    -r|--reset)
        git config --remove-section timetrack 2>/dev/null
        ;;

    -e|--set)
        git config --remove-section timetrack 2>/dev/null
        git config timetrack.spent $(( $2 * 60 ))
        ;;

    -a|--amend)
        git timetrack -p > /dev/null
        spent=$(git config timetrack.spent)
        hacking=$(git config --get timetrack.hacking)
        git config --remove-section timetrack 2> /dev/null

        if [ $spent ]
        then
            git notes --ref timetracker add -f -m "Time-spent: $spent" $2
        fi
        if [ $hacking ]
        then
            git config timetrack.start $(date +%s)
            git config timetrack.hacking $hacking
        fi
        ;;

    -d|--delete)
        git notes --ref timetracker remove $2
        ;;

    -u|--summary)
        shift
        allusers=$(git log --oneline --pretty="format: %an <%ae>" $* | sort | uniq)
        alltimes=$(git log $* | grep "Time-spent:"  | cut -d":" -f2)

        total=0
        for t in $alltimes
        do
            total=$(( $total + $t ))
        done

        echo "total time spent by authors"
        printf "$allusers\n" | while read author
        do
            dedication=$(user_time_dedication "$author" $*)
            [ $dedication -ne 0 ] && printf " %-49s %s\n" "$author" "$(human_time $dedication)"
        done

        printf "\n%-50s %s\n" "total time spent in this project" "$(human_time $total)"
        printf "%-50s %s\n" "time spent in next comit" "$(human_time $(current_time))"

        hacking=$(git config --get timetrack.hacking)
        if [ $hacking ]
        then
            echo "hacking mode activated"
        fi
        ;;

    -l|--log)
        shift
        git log --color $* | sed "s/Time-spent: \([0-9]\+\)/git timetrack --human-time \1/e" | less -R
        ;;

    --human-time)
        echo "    Time-spent: "$(human_time $2)
        ;;

    -o|--addhooks)

        gitdir="$(git rev-parse --git-dir)/hooks"
        if [ -d $gitdir ]
        then
            githook="$gitdir/post-commit"

            echo '#!/bin/bash

hacking=$(git config timetrack.hacking)
git timetrack -p > /dev/null
spent=$(git config timetrack.spent)
git config --remove-section timetrack 2> /dev/null

if [ $spent ]
then
    git notes --ref timetracker add -m "Time-spent: $spent"

    if [ $hacking ]
    then
        git config timetrack.start $(date +%s)
        git config timetrack.hacking $hacking
    fi
fi' > $githook

            chmod +x $githook

            githook="$gitdir/post-merge"

            echo '#!/bin/bash

GITDIR=$(git rev-parse --git-dir)
for remote in $GITDIR/refs/notes/remotes/*
do
    remote_ref="refs/notes/remotes/$(basename $remote)/timetracker"
    git notes --ref timetracker merge $remote_ref
done' > $githook

            chmod +x $githook
            echo "hooks created"
        else
            echo "That isn't a git root directory. I wont do anything"
        fi
        ;;

    -n|--config)
        remote=$2
        if [ -z $remote ]
        then
            remote=origin
        fi

        git config --add remote.$remote.push "refs/notes/timetracker:refs/notes/timetracker"
        git config --add remote.$remote.push "refs/heads/master:refs/heads/master"
        git config --add remote.$remote.fetch "+refs/notes/timetracker:refs/notes/remotes/$remote/timetracker"
        git config notes.rewriteRef "refs/notes/timetracker"
        git config notes.displayRef "refs/notes/timetracker"

        echo "git timetrack configured, now, run git pull if you don't want problems"
        ;;

    -i|--init)
        git timetrack --addhooks
        git timetrack --config
        ;;
    *)
        show_help
        ;;
esac
