#!bin/bash

# For example in a normal linux distro:
#
# $ sudo cp git-timetrack /usr/local/bin/

# To use it you should add the post-commit hook to your project. You
# can do it running timetrack addhook inside your project dir.
#
# $ git timetrack addhook

cp git-timetrack /usr/local/bin
