#!/bin/bash

git timetrack -p > /dev/null
spent=$(git config --local timetrack.spent)
git config --local --remove-section timetrack 2> /dev/null

if [ $spent ]
then
    git notes add -m "Time-spent: $spent"
fi
